# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        include_format: null
    view:
        view_response_listener:  force
        formats:
            json: true
    format_listener:
        rules:
         - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    exception:
        enabled: true
