register:
    path: /api/register
    controller: App\Controller\Auth\AuthController::register
    methods: POST

api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

posts:
    type: rest
    resource: App\Controller\PostController
    prefix: api
